# fly.toml app configuration file generated for geocaching-app-paas02 on 2025-01-12T20:18:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'geocaching-app-paas02'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
